SLRAD.prototype.setTree=function(a){this.tree=a};
function slradTree(a){var b=this,c=new SLRAD;c.setTree(b);a.data("slrad",c);this.element=a;this.id=a.attr("id");this.actionUrl=a.attr("actionUrl");this.datasource=a.attr("datasource");this.nodeIdField=a.attr("nodeIdField");this.nodeTextField=a.attr("nodeTextField");this.parentIdField=a.attr("parentIdField");(this.datasourceArgs=a.attr("datasourceArgs"))&&this.element.data("datasourceArgs",SL.parseJson(this.datasourceArgs));this.useCheckbox=a.attr("useCheckbox");this.useLiteCheckbox=a.attr("useLiteCheckbox");
this.noCtxMenu=a.attr("noCtxMenu");this.autoOpen=a.attr("autoOpen");this.autoSelectRoot=a.attr("autoSelectRoot");this.nodeMoveType=(a.attr("nodeMoveType")||"inside").split(",");this.nodeMoveServcie=a.attr("nodeMoveServcie");this.nodeCopyService=a.attr("nodeCopyService");this.treeStyle=a.attr("treeStyle")||"default";this.clickAction=$("#"+a.attr("clickAction"));this.dblClickAction=$("#"+a.attr("dblClickAction"));b.clickAction.length>0&&b.element.bind("select_node.jstree",function(){b.element.jstree("get_selected").length!=
0&&b.clickAction.click()});b.dblClickAction.length>0&&b.element.bind("dblclick.jstree",function(){b.element.jstree("get_selected").length!=0&&b.dblClickAction.click()});b.element.bind("move_node.jstree",function(a,c){var d=$(this),e=$.jstree._reference(d)._get_move(),d=e.o,f=e.np,e=e.cy,j=c.rlbk;if(e&&!b.nodeCopyService||!e&&!b.nodeMoveServcie)return $.jstree.rollback(j),!1;var g={};g[b.nodeIdField]=d.attr("nodeId");g["target."+b.nodeIdField]=f.attr("nodeId");g[b.parentIdField]=d.attr("parentId");
g["target."+b.parentIdField]=f.attr("parentId");b.nodeTextField&&(g[b.nodeTextField]=b.element.jstree("get_text",d),g["target."+b.nodeTextField]=b.element.jstree("get_text",f));if(b.initParam)g[b.initParam]=b.initValue;g[SL.KEYS.SERVICE]=e?b.nodeCopyService:b.nodeMoveServcie;$.post(b.actionUrl,g,function(a){a.success?(a.message&&SL.info(a.message),a.dataObject&&(a=b.convertData(a.dataObject,!0),b.element.data("tree",a),b.element.jstree("refresh"))):(a.message&&SL.error(a.message),$.jstree.rollback(j))},
"json");SL.debugEnable&&SL.debug("move node '"+b.element.jstree("get_text",d)+"<"+d.attr("nodeId")+">' to '"+b.element.jstree("get_text",f)+"<"+f.attr("nodeId")+">'")});this.ctxMenuItems={};a=$("div.DMC[treeId='"+b.id+"']");if(a.length>0){var a=$("*[service],*[nextview],*[cascadeTo]",a),e=0;$.each(a,function(){var a=$(this);e++;b.ctxMenuItems[a.val()]={label:a.val(),action:function(){a.is(":visible ")&&a.is(":enabled")&&a.click()},separator_after:e%3==0}})}a=["themes","json_data","ui","search"];if(b.nodeCopyService||
b.nodeMoveServcie)a.push("dnd"),a.push("crrm");b.useCheckbox?a.push("checkbox"):b.useLiteCheckbox&&a.push("lite_checkbox");b.noCtxMenu||a.push("contextmenu");b.element.jstree({plugins:a,themes:{theme:b.treeStyle},json_data:{data:function(){return b.element.data("tree")||{}},progressive_render:!0},crrm:{move:{default_position:"inside",check_move:function(a){return(b.nodeMoveServcie||b.nodeCopyService)&&$.inArray(a.p,b.nodeMoveType)!=-1}}},contextmenu:{select_node:!0,items:function(){return b.ctxMenuItems}}});
var d;b.element.one("reopen.jstree",function(a){SL.debug(a.type);d&&window.clearTimeout(d);d=window.setTimeout(function(){b.element.jstree("select_node",$("li:first",b.element),!1,$.noop)},300)})}
slradTree.prototype.convertData=function(a,b){var c=this,e=function(a){if(!a.children||a.children.length<1)return!1;var h=[];$.each(a.children,function(a,d){if(d.nodeId&&d.nodeText){var i={data:d.nodeText,attr:{nodeId:d.nodeId,parentId:d.parentId}};b&&c.element.jstree("is_open","[nodeId='"+d.nodeId+"'][parentId='"+d.parentId+"']")&&(i.state="open");var f=e(d);f&&f.length>0&&(i.children=f);h.push(i)}else h.push(e(d))});return h};return(a.nodeId&&a.nodeText?{data:a.nodeText,attr:{nodeId:a.nodeId},state:b&&
c.element.jstree("is_open","[nodeId='"+a.nodeId+"']:not([parentId])")?"open":"closed",children:e(a)}:e(a))||{data:"(\u672a\u547d\u540d)",attr:{nodeId:a.nodeId}}};
slradTree.prototype.initData=function(){var a=this;a.element.trigger("beforeInitData");var b={};b[SL.KEYS.SERVICE]=a.datasource;if(a.datasourceArgs){var c=a.element.data("datasourceArgs");$.extend(b,c);if(c.origin_args)b.origin_args=void 0,$.extend(b,a.element.data("cascadeArgs"));jQuery.ajaxSettings.traditional=!0}$.post(a.actionUrl,b,function(b){if(b.success){if(b.dataObject){var d=a.convertData(b.dataObject,!!a.element.data("tree"));a.element.data("tree",d);a.element.jstree("refresh");a.autoOpen&&
a.element.jstree("open_all",a.autoOpen)}a.element.trigger("afterInitData",b)}else SL.error(b.message||"\u6811\u6570\u636e\u52a0\u8f7d\u5931\u8d25",b.props&&b.props.loginUrl)},"json")};
slradTree.prototype.getStateParams=function(){var a=this,b={},c={},e=a.element.jstree("get_selected");e.each(function(){var b=$(this);c[a.nodeIdField]||(c[a.nodeIdField]=[]);c[a.nodeIdField].push(b.attr("nodeId"));c[a.parentIdField]||(c[a.parentIdField]=[]);c[a.parentIdField].push(b.attr("parentId"));a.nodeTextField&&(c[a.nodeTextField]||(c[a.nodeTextField]=[]),c[a.nodeTextField].push(a.element.jstree("get_text",b)))});b.keys=c;var d={};d.pickedItemNum=e.length;b.props=d;b.dataCallbacks={pundefined:function(){a.refresh()}};
return b};
slradTree.prototype.refresh=function(a){var b=this,c=b.getStateParams().keys[b.nodeIdField],e=a||c&&c[0];b.element.trigger("beforeInitData");a={};a[SL.KEYS.SERVICE]=b.datasource;if(b.initParam)a[b.initParam]=b.initValue;$.post(b.actionUrl,a,function(a){if(a.success){a.message&&SL.info(a.message);if(a.dataObject){var c=b.convertData(a.dataObject,!0);b.element.data("tree",c);b.element.one("refresh.jstree",function(){window.setTimeout(function(){b.element.jstree("select_node",$("li[nodeId='"+e+"']",
b.element),!1,$.noop)},300)});b.element.jstree("refresh")}b.element.trigger("afterInitData",a)}else a.message&&SL.error(a.message),$.jstree.rollback(rollback)},"json")};
$(document).ready(function(){$(document).data("slrad_tree")||($(document).data("slrad_tree",!0),SL.loadScript(SL.getRootPath()+"/jstree/jquery.jstree.js",function(){$("div.Tree").each(function(){var a=$(this),b=new slradTree(a);$("[cascadeTo='"+a.attr("id")+"']").length>0?a.bind("cascadeInited",function(){b.initData()}):b.initData()})}),$(document).trigger("slrad_tree_ready"))});
