var SLRAD_JS_VERSION=1.5,SLRAD_JS_DATE=20140328;function SLRAD(){this.debugEnable=!0}SLRAD.prototype.getRootPath=function(){if(window.SLRAD_ROOT)return window.SLRAD_ROOT;var a=window.document.location.href,b=window.document.location.pathname,c=a.indexOf(b),a=a.substring(0,c),b=b.substring(0,b.substr(1).indexOf("/")+1);return a+b+"/js/slrad"};
SLRAD.prototype.loadScript=function(a,b){if($("script[src='"+a+"']").length>0)b&&b();else{var c=document.createElement("script");c.type="text/javascript";if(b)c.onload=c.onreadystatechange=function(){if(!c.readyState||!(c.readyState!="loaded"&&c.readyState!="complete"))c.onreadystatechange=c.onload=null,b()};c.src=a;$("head")[0].insertBefore(c,$("head script[src$='slrad.js']")[0])}};
SLRAD.prototype.loadStyle=function(a){$("head link[href='"+a+"']").length>0||(a=$('<link href="'+a+'" type="text/css" rel="stylesheet"/>'),$("head").prepend(a))};
SLRAD.prototype.loadJQueryUI=function(a){$("head link[href$='.css'][href*='jquery-ui']").length<=0&&SL.loadStyle(SL.getRootPath()+"/jqueryui/css/smoothness/jquery-ui.css");if($("head script[src$='.js'][src*='jquery-ui']").length<=0)SL.loadScript(SL.getRootPath()+"/jqueryui/jquery-ui.js",function(){window.setTimeout(function(){$(document).trigger("jqueryui_loaded");a()},100)});else if(a)var b=window.setInterval(function(){window.$&&$.ui&&$.ui.version&&$.effects.version&&(window.clearInterval(b),window.setTimeout(function(){$(document).trigger("jqueryui_loaded");
a()},10))},10)};SLRAD.prototype.wait=function(a,b){$(document).queue("slrad_wait",function(){window.setTimeout(function(){$(document).dequeue("slrad_wait")},a)});$(document).queue("slrad_wait",function(){b()});$(document).dequeue("slrad_wait")};
SLRAD.prototype.KEYS={SERVER_START:"server.start",SERVER_STOP:"server.stop",SERVER_STATE:"server.state",USER_IN_SESSION:"sl.current_user",CONFIGURATOR:"sl.configurator",SERVICE:"sl.service",RESULT:"sl.result",RESULT_VIEW:"sl.result_view",FILTER_WHERE:"sl.filter_where",PAGE_NUM:"sl.page_num",PAGE_SIZE:"sl.page_size",PERMISSION:"sl.pid",PERMISSION_SERVICE:"service.permission",PERMISSON_LIST_SERVICE:"service.permissionList"};window.SL=new SLRAD;
SLRAD.prototype.jsonToString=function(a){var b="";$.each(a,function(a,d){$.each(d,function(d,f){b+="&"+a+"="+f})});b.length>0&&(b=b.substring(1));return b};SLRAD.prototype.parseJson=function(a){if(typeof a=="object")return a;var b={};if(a)try{a.indexOf("{")==-1&&(a="{"+a+"}"),b=window.eval("("+a+")")}catch(c){if(SL.debugEnable)throw SL.error("\u89e3\u6790Json\u5b57\u7b26\u4e32'"+a+"'\u53d1\u751f\u5f02\u5e38\uff01"),c;}return b};SLRAD.prototype.info=function(a,b){window.alert(a);b&&b()};
SLRAD.prototype.error=function(a,b){if(!window.top.showErroring&&(window.top.showErroring=!0,alert(a),window.setTimeout(function(){window.top.showErroring=!1},10),b))window.top.location=b};SLRAD.prototype.confirm=function(a){return window.confirm(a)};
SLRAD.prototype.debug=function(a){if(SL.debugEnable){window.console&&window.console.log&&window.console.log(a);var b=$("<div>",{"class":"slrad_debug",style:"display:none;max-width:80%;height:auto;word-wrap:break-word;overflow:hidden;background-color:#EEEE00;position:absolute;right:0px;top:0px;marggin:2px;padding:1px",onclick:function(){$(this).remove()}});b.appendTo("body");b.text(a);var c=0;$(".slrad_debug").each(function(){c+=$(this).height()+4});c-=b.height();b.fadeIn(100).animate({top:c},500);
window.setTimeout(function(){b.hide(500,function(){b.remove()})},1E4)}};SLRAD.prototype.showLoading=function(){var a=$("#slrad_loading");a.length==0&&(a=$('<div id="slrad_loading" style="display:none;top:50%; left:50%;position:absolute;width:100px;height:100px; margin:-50px -50px;z-index:999999"><img alt="loading" src="'+SL.getRootPath()+'/loading.gif"></div>').prependTo(document.body));a.fadeIn(500);this.loading=a};SLRAD.prototype.hideLoading=function(){this.loading&&this.loading.fadeOut(100)};
SLRAD.prototype.openWindow=function(a,b,c,d,g,f,h,i){var e=SL.getColorboxTopWindow();e.$("iframe[name='"+e._colorbox_iframe_name+"']").removeAttr("src");e.$(e).unbind("iframe_form_saved");e.iframe_saved_state=!1;var j={transition:"none",title:a,width:b,height:c,iframe:!0,href:f||"",opacity:g||0.85,overlayClose:!1,close:"\u5173\u95ed",onComplete:function(){e._colorbox_opened=!0;h&&h()},onClosed:function(){e._colorbox_opened=!1;e.iframe_saved_state&&i&&i()}};ajax_load_colorbox_css(e,d?d:"5",function(){e.$.colorbox.remove();
e.$.colorbox(j)})};SLRAD.prototype.getColorboxFrameName=function(){return SL.getColorboxTopWindow()._colorbox_iframe_name};SLRAD.prototype.getColorboxTopWindow=function(){for(var a=window.top,b=window;b!=a;){var c=b.parent;if(c._colorbox_opened)break;b=c}return b};SLRAD.prototype.closeWindow=function(){var a=SL.getColorboxTopWindow()._colorbox_opened?window:window.parent;a._colorbox_opened=!1;a.$("div#cboxClose").click()};
function ajax_load_colorbox_css(a,b,c){var d=function(b){a.$("#colorbox_style").remove();var d=a.$('<style type="text/css" id="colorbox_style">');d[0].styleSheet?d[0].styleSheet.cssText=b:d[0].appendChild(a.document.createTextNode(b));a.$("head").append(d);c&&c()},g=SL.getRootPath()+"/colorbox/style"+b+"/",b=g+"colorbox.css",f=a.$("head").data(b);f?d(f):$.get(b,{},function(b){b=b.replace(/url\(images/g,"url("+g+"images");a.$("head").data(b);d(b)},"text")}
$(document).ready(function(){if(!$(document).data("slrad"))$(document).data("slrad",!0),$("head link.colorbox").length==0&&ajax_load_colorbox_css(window,5,function(){SL.loadScript(SL.getRootPath()+"/colorbox/jquery.colorbox.js")}),SL.debugEnable=window.SLRAD_DEBUG?!0:!1,$(document).click(function(){$(".slrad_debug").hide(500,function(){$(".slrad_debug").remove()})}),$(document).ajaxStart(function(){SL.showLoading()}),$(document).ajaxStop(function(){SL.hideLoading()}),$(document).ajaxComplete(function(a,
b,c){SL.debugEnable&&SL.debug("AjaxPost:"+decodeURI(c.data))}),$(document).trigger("slrad_ready")});
