SLRAD.prototype.setDMC=function(a){this.dmc=a};
function slradDmcAction(a,b){this.dmc=b;this.id=a.attr("id");this.element=a;var c=this;this.name=a.attr("value");this.title=a.attr("title");if(!this.title)this.title=this.name;this.target=a.attr("target");this.actionArgs={};a.click(function(){var a=c.element.attr("actionArgs");if(a)c.actionArgs=SL.parseJson(a)});this.service=a.attr("service");this.nextview=a.attr("nextview");this.cascadeTo=a.attr("cascadeTo");this.confirm=!!a.attr("confirm");this.check=a.attr("check");this.nextdatapage=a.attr("nextdatapage");
var d=a.attr("windowSize"),d=d?d.split(","):[];this.windowWidth=d[0]||"80%";this.windowHeight=d[1]||"80%"}
slradDmcAction.prototype.checkAndConfirm=function(){var a=this.dmc.dataStateParams;if(this.check){var b=null;this.check=="1"&&a.props.pickedItemNum!=1?a.props.pickedItemNum>1?b="\u5bf9\u4e0d\u8d77\uff0c["+this.name+"]\u64cd\u4f5c\u53ea\u5141\u8bb8\u9009\u62e9\u4e00\u6761\u6570\u636e!":a.props.pickedItemNum<1&&(b="\u5bf9\u4e0d\u8d77\uff0c["+this.name+"]\u64cd\u4f5c\u9700\u8981\u5148\u9009\u62e9\u4e00\u6761\u6570\u636e!"):this.check=="m"&&a.props.pickedItemNum<1?b="\u5bf9\u4e0d\u8d77\uff0c["+this.name+
"]\u64cd\u4f5c\u9700\u8981\u5148\u9009\u62e9\u4e00\u6761\u6216\u591a\u6761\u6570\u636e!":this.check=="w"&&!a[SL.KEYS.FILTER_WHERE]&&(b="\u5bf9\u4e0d\u8d77\uff0c["+this.name+"]\u64cd\u4f5c\u9700\u8981\u5148\u8bbe\u5b9a\u7b5b\u9009\u6761\u4ef6!");if(b)return SL.error(b),!1}if(this.confirm&&(b="\u60a8\u786e\u8ba4\u8fdb\u884c["+this.name+"]\u64cd\u4f5c\u5417?",this.check=="w"&&(b+="\n\u64cd\u4f5c\u6761\u4ef6\uff1a"+a.props.where_desc,b+="\n\u64cd\u4f5c\u5f71\u54cd\u8bb0\u5f55\u6570\uff1a"+a.props.totalRows),
!SL.confirm(b)))return!1;return!0};
slradDmcAction.prototype.clickServerHandler=function(){var a=this,b=this.dmc,c=b.dataStateParams,d=$("<form>",{slradjs:"actionform",action:b.actionUrl+"?"+(new Date).getTime(),method:"post",style:"display:none"});a.service&&$("<input>",{type:"hidden",name:SL.KEYS.SERVICE,value:a.service}).appendTo(d);a.nextview&&$("<input>",{type:"hidden",name:SL.KEYS.RESULT_VIEW,value:a.nextview}).appendTo(d);(a.check=="1"||a.check=="m"||a.check=="n")&&$.each(c.keys,function(a,b){$.each(b,function(b,c){$("<input>",
{type:"hidden",name:a,value:c}).appendTo(d)})});$.each(a.actionArgs,function(a,b){$("<input>",{type:"hidden",name:a,value:b}).appendTo(d)});if(b.getDataComponent().datasourceArgs){var e=b.getDataComponent().element.data("datasourceArgs");$.each(e,function(a,b){$("<input>",{type:"hidden",name:a,value:b}).appendTo(d)});e.origin_args&&($("[name='origin_args']",d).remove(),$.each(b.getDataComponent().element.data("cascadeArgs"),function(a,b){$("<input>",{type:"hidden",name:a,value:b}).appendTo(d)}))}(a.check==
"w"||a.check=="n")&&c[SL.KEYS.FILTER_WHERE]&&$("<input>",{type:"hidden","class":"where",name:SL.KEYS.FILTER_WHERE,value:c[SL.KEYS.FILTER_WHERE]}).appendTo(d);var f=c.dataCallbacks["p"+a.nextdatapage]||$.noop;a.nextview?(d.appendTo(b.element),a.service||(c="?",a.nextview.indexOf(c)>-1&&(c="&"),c=a.nextview+c+(new Date).getTime(),d.attr("action",c)),c=SL.getColorboxFrameName(),a.target?/[_]/g.test(a.target)||$("iframe[name='"+a.target+"']").show():a.target=c,d.attr("target",a.target),a.target==c?SL.openWindow(a.title,
a.windowWidth,a.windowHeight,b.windowStyle,b.windowOpacity,"about:blank",function(){window.setTimeout(function(){d.submit();d.remove()},1)},f):(b=window.parent,b.$(b).unbind("iframe_form_saved"),a.target=="_self"||a.target=="_top"||a.target=="_parent"||b.$(b).bind("iframe_form_saved",function(){f()}),d.submit(),d.remove())):$.post(b.actionUrl,d.serialize(),function(b){a.element.trigger("afterAction",b);b.success?(b.message&&SL.info(b.message),f()):SL.error(b.message||"ActionButton\u64cd\u4f5c\u5931\u8d25\uff01",
b.props&&b.props.loginUrl)},"json")};slradDmcAction.prototype.clickCascadeHandler=function(){var a=this,b=this.dmc,c=$("#"+this.cascadeTo),d=b.dataStateParams;if((b=c.data("datasourceArgs"))&&b.origin_args){var e={};$.each(b.origin_args,function(b,c){e[c]=a.actionArgs&&a.actionArgs[b]||d&&(d.keys&&d.keys[b]||d.datas&&d.datas[b])});c.data("cascadeArgs",e)}c.show();c.trigger("cascadeInited")};
function slradDMC(a){var b=this,c=new SLRAD;c.setDMC(b);a.data("slrad",c);this.element=a;this.id=a.attr("id");this.actionUrl=a.attr("actionUrl")||a.attr("acitonUrl");this.permissionId=a.attr("permissionId");this.dataGridId=a.attr("dataGridId");this.treeId=a.attr("treeId");this.windowOpacity=a.attr("windowOpacity");this.windowStyle=a.attr("windowStyle")||"5";this.dataStateParams={};$("*[service],*[nextview],*[cascadeTo]",b.element).each(function(){var a=new slradDmcAction($(this),b);$(this).click(function(){var c=
$(this);if(!c.prop("disabled")){b.dataStateParams=b.getDataComponent().getStateParams();if(!a.checkAndConfirm())return!1;if(a.element.triggerHandler("beforeAction",b.dataStateParams)===!1)return!1;c.is("[service],[nextview]")&&a.clickServerHandler();c.is("[cascadeTo]")&&(a.clickCascadeHandler(),a.element.trigger("afterAction",b.dataStateParams))}})})}
slradDMC.prototype.getDataComponent=function(){var a=void 0;if(this.dataGridId)a=$("#"+this.dataGridId).data("slrad").dataGrid;else if(this.treeId)a=$("#"+this.treeId).data("slrad").tree;return a};
slradDMC.prototype.initData=function(){var a=this;if(a.permissionId){var b={};b[SL.KEYS.SERVICE]=SL.KEYS.PERMISSION_SERVICE;b[SL.KEYS.PERMISSION]=a.permissionId;$.post(a.actionUrl,b,function(b){b.success?(b.dataObject&&($.each(b.dataObject,function(b,c){c=="*"?$("*[service],*[nextview]",a.element).show().prop("disabled",!1):($("[service='"+c+"']",a.element).attr("sl_perm_serivce","1"),$("[nextview='"+c+"']",a.element).attr("sl_perm_nextview","1"))}),$("[service][nextview][sl_perm_serivce][sl_perm_nextview]").show().prop("disabled",
!1),$("[service][sl_perm_serivce]:not([nextview])").show().prop("disabled",!1),$("[nextview][sl_perm_nextview]:not([service])").show().prop("disabled",!1)),a.element.trigger("afterInitData",b)):SL.error(b.message||"\u4e1a\u52a1\u6743\u9650\u5217\u8868\u52a0\u8f7d\u5931\u8d25",b.props&&b.props.loginUrl)},"json")}};$(document).ready(function(){$(document).data("slrad_dmc")||($(document).data("slrad_dmc",!0),$("div.DMC").each(function(){var a=$(this);(new slradDMC(a)).initData()}),$(document).trigger("slrad_dmc_ready"))});
